In [3]:
#展示zip使用,zip功能是创建一个迭代器，迭代器返回的是元组，元组中的元素是两个列表中对应位置的元素。
a=[1, 2, 3]
b=[4, 5, 6]
list(zip(a, b))

[(1, 4), (2, 5), (3, 6)]

In [8]:
a

[1, 2, 3]

In [5]:
import time
import numpy as np

# 列表处理1000万个数字的加法（慢，需循环）
time1 = time.time()
list1 = [i for i in range(10000000)]
list2 = [i*2 for i in range(10000000)]
result = [a + b for a, b in zip(list1, list2)]  # 需循环
time2 = time.time()
print(f"列表处理100万个数字的加法耗时：{time2-time1}")

# NumPy数组处理（快，直接运算）
arr1 = np.arange(10000000)
arr2 = np.arange(10000000) * 2
result = arr1 + arr2  # 无需循环，直接矢量化运算
time3 = time.time()
print(f"NumPy数组处理100万个数字的加法耗时：{time3-time2}")

列表处理100万个数字的加法耗时：1.2044694423675537
NumPy数组处理100万个数字的加法耗时：0.100250244140625


# 使用列表创建ndarray

In [7]:
# 创建一个一维ndarray
arr1 = np.array([1, 2, 3])
print(arr1) #数组输出没有逗号
print(type(arr1))

# 创建一个二维ndarray
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)
print(type(arr2))

# 创建一个三维ndarray
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr3)
print(type(arr3))

[1 2 3]
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
<class 'numpy.ndarray'>


# 数组创建

In [9]:
print(np.zeros((2)))				# 创建一个2行3列全0数组
print(np.ones((3, 2)))  			# 创建一个3行2列全1数组
np.empty((2,3))				# 创建一个2行3列，元素值内容随机且依赖于内存状态的数组

[0. 0.]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


array([[1., 1., 1.],
       [1., 1., 1.]])

In [14]:
arr4 = np.arange(0, 10, 2, dtype=np.float32)
arr4

array([0., 2., 4., 6., 8.], dtype=float32)

In [15]:
arr4 = np.matrix([[1, 2, 3], [4, 5, 6]]) #不常用
arr4

matrix([[1, 2, 3],
        [4, 5, 6]])

# 随机生成数组

In [17]:
# 1. 创建一个0-1的随机数矩阵, 矩阵是2行3列
arr5 = np.random.random((2,3))
print(arr5)
print(type(arr5))

# 2. 创建一个0-10的随机整数矩阵, 矩阵是2行3列
arr6 = np.random.randint(0, 10, (2,3))
print(arr6)
print(type(arr6))

# 3. 创建一个0-10的随机浮点数矩阵, 矩阵是2行3列
arr7 = np.random.uniform(0, 10, (2,3))
print(arr7)
print(type(arr7))

[[0.45282588 0.00176581 0.8620153 ]
 [0.80056935 0.83331982 0.50362949]]
<class 'numpy.ndarray'>
[[0 6 7]
 [0 4 9]]
<class 'numpy.ndarray'>
[[9.86224298 6.45958507 8.38167089]
 [9.94297694 2.36157232 9.34780849]]
<class 'numpy.ndarray'>


# 数组的属性

In [19]:
# 创建一个2行3列的矩阵、
arr8 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr8.shape)
print(arr8.ndim)
print(arr8.dtype)
print(arr8.size)

(3, 3)
2
int32
9
