## 4.1 形状改变

In [3]:
import numpy as np

# 初始化一维ndarray
arr_1d = np.arange(12)          # 生成 0~11 的一维数组
print(arr_1d)
# reshape变形为二维（例如 3 行 4 列）
arr_2d = arr_1d.reshape(3, 4)   

print(arr_2d)


[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [6]:
from re import A


arr_1d = arr_2d.reshape(-1,order='C')
arr_1d
#一个数组变形为高维后，再变形回去，元素位置不变

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

## 4.2 类型变换

In [8]:
import numpy as np

# 初始化一个整型数组
arr_int = np.array([1, 2, 3, 4, 5], dtype=np.int32)


# astype变为浮点类型并输出
arr_float = arr_int.astype(np.float32)
print(arr_float)


[1. 2. 3. 4. 5.]


## 4.3 索引与切片

In [9]:
# 1. 列表的索引与切片
# list[start:end:step]
arr = [1, 2, 3, 4, 5, 6]
print(arr[0:4:2])           # 1,3

# 2. 一维ndarray的索引与切片， 和列表的索引与切片一样
arr14 = np.arange(0, 12)
print(arr14[0:4:2])         # [0,2]

[1, 3]
[0 2]


In [10]:
# 3. 多维ndarray的索引与切片
arr15 = np.arange(0, 12).reshape(3,4)
print(arr15)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [12]:
# 假设 arr15 是一个二维 NumPy 数组
import numpy as np

# 取第 3 行（索引从 0 开始）
row_3 = arr15[2, :]
print("row_3:", row_3)

# 取第 4 列
col_4 = arr15[:, 3]
print("col_4:", col_4)

# 取不连续的多行：第 1、3行
rows_135 = arr15[[0, 2], :]
print("rows_135:", rows_135)

# 取不连续的多列：第 2、4列
cols_246 = arr15[:, [1, 3]]
print("cols_246:", cols_246)

# 取某个元素：第 2 行第 3 列的元素
element = arr15[1, 2]
print("element:", element)

# 取连续的多行：第 2 到 4 行（索引 1 到 3）
rows_2to4 = arr15[1:, :]
print("rows_2to4:", rows_2to4)

# 取连续的多列：第 2 到 3 列（索引 1 到 2）
cols_2to3 = arr15[:, 1:3]
print("cols_2to3:", cols_2to3)

#总结，左闭右开，逗号前面是行操作，后面是列操作



row_3: [ 8  9 10 11]
col_4: [ 3  7 11]
rows_135: [[ 0  1  2  3]
 [ 8  9 10 11]]
cols_246: [[ 1  3]
 [ 5  7]
 [ 9 11]]
element: 6
rows_2to4: [[ 4  5  6  7]
 [ 8  9 10 11]]
cols_2to3: [[ 1  2]
 [ 5  6]
 [ 9 10]]


## 4.4 元素修改

In [13]:
# 修改单个值
arr15 = np.arange(0, 12).reshape(3,4)
arr15[1, 2] = 100
print("修改单个值后:\n", arr15)

# 重新初始化
arr15 = np.arange(0, 12).reshape(3,4)
# 修改某一行的值
arr15[1, :] = 100
print("修改第2行值后:\n", arr15)

# 重新初始化
arr15 = np.arange(0, 12).reshape(3,4)
# 修改某一列的值
arr15[:, 2] = 100
print("修改第3列值后:\n", arr15)

# 重新初始化
arr15 = np.arange(0, 12).reshape(3,4)
# 修改局部块值
arr15[0:2, 1:3] = 100
print("修改局部块值后:\n", arr15)


修改单个值后:
 [[  0   1   2   3]
 [  4   5 100   7]
 [  8   9  10  11]]
修改第2行值后:
 [[  0   1   2   3]
 [100 100 100 100]
 [  8   9  10  11]]
修改第3列值后:
 [[  0   1 100   3]
 [  4   5 100   7]
 [  8   9 100  11]]
修改局部块值后:
 [[  0 100 100   3]
 [  4 100 100   7]
 [  8   9  10  11]]


In [14]:
import numpy as np
# 第一次修改：将不相邻的多个位置改为100
arr15 = np.arange(0, 12).reshape(3, 4)
arr15[[0,0],[2,3]] = 100
print(arr15)

# 重新初始化
arr15 = np.arange(0, 12).reshape(3, 4)

# 第二次修改：将大于5的元素改为0
arr15[arr15 > 5] = 0
print("第二次修改后：")
print(arr15)

# 重新初始化
arr15 = np.arange(0, 12).reshape(3, 4)
result=np.where(arr15 > 5, True, False)
print(result)
print(arr15)


[[  0   1 100 100]
 [  4   5   6   7]
 [  8   9  10  11]]
第二次修改后：
[[0 1 2 3]
 [4 5 0 0]
 [0 0 0 0]]
[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [15]:
arr15 = np.arange(0, 12).reshape(3, 4)
arr15>5

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

## 5.1 元素的运算

In [17]:
arr16 = np.arange(0, 12).reshape(3,4)
print("原始数组:\n", arr16)

# 加法：每个元素加10
add_result = arr16 + 10
print("加法结果:\n", add_result)

# 减法：每个元素减5
sub_result = arr16 - 5
print("减法结果:\n", sub_result)

# 乘法：每个元素乘以2
mul_result = arr16 * 2
print("乘法结果:\n", mul_result)

# 除法：每个元素除以3
div_result = arr16 / 3
print("除法结果:\n", div_result)


原始数组:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
加法结果:
 [[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
减法结果:
 [[-5 -4 -3 -2]
 [-1  0  1  2]
 [ 3  4  5  6]]
乘法结果:
 [[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]
除法结果:
 [[0.         0.33333333 0.66666667 1.        ]
 [1.33333333 1.66666667 2.         2.33333333]
 [2.66666667 3.         3.33333333 3.66666667]]


## 5.2 数组的运算

In [18]:
import numpy as np

# 创建两个相同形状（3行4列）的数组
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

b = np.array([[12, 11, 10, 9],
              [8, 7, 6, 5],
              [4, 3, 2, 1]])

# 加减乘除
add_result = a + b
sub_result = a - b
mul_result = a * b
div_result = a / b

print("加法结果:\n", add_result)
print("减法结果:\n", sub_result)
print("乘法结果:\n", mul_result)
print("除法结果:\n", div_result)


加法结果:
 [[13 13 13 13]
 [13 13 13 13]
 [13 13 13 13]]
减法结果:
 [[-11  -9  -7  -5]
 [ -3  -1   1   3]
 [  5   7   9  11]]
乘法结果:
 [[12 22 30 36]
 [40 42 42 40]
 [36 30 22 12]]
除法结果:
 [[ 0.08333333  0.18181818  0.3         0.44444444]
 [ 0.625       0.85714286  1.16666667  1.6       ]
 [ 2.25        3.33333333  5.5        12.        ]]


In [19]:
#不同尺寸不可以运算
arr19 = np.arange(0, 12).reshape(3,4)
arr20 = np.arange(0, 4).reshape(2,2)
# arr19 + arr20

ValueError: operands could not be broadcast together with shapes (3,4) (2,2) 

### 5.2.2 数组尺寸不同时进行运算

In [21]:
# 当某一个轴的尺寸不同时，另一个轴的尺寸必须为1，才能进行运算
arr21 = np.arange(0, 12).reshape(3,4)       # 3行4列
print(arr21)
arr22 = np.arange(0, 4).reshape(1,4)                     # 1行4列
print(arr22)
print(arr21 + arr22)                       

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[0 1 2 3]]
[[ 0  2  4  6]
 [ 4  6  8 10]
 [ 8 10 12 14]]


In [22]:
import numpy as np

# 3行4列矩阵
A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

# 3行1列矩阵（列向量）
B = np.array([[1],
              [2],
              [3]])

# 广播运算：3x4 与 3x1 逐元素相加
result = A + B
print("A + B =\n", result)



A + B =
 [[ 2  3  4  5]
 [ 7  8  9 10]
 [12 13 14 15]]


In [30]:
import numpy as np

# 初始化为整型
a = np.random.randint(0, 10, size=(2, 3, 4))
b = np.random.randint(0, 10, size=(1, 3, 4))

# print(a)
# print(b)
# 广播机制自动扩展 b 的维度，使 shape(1,3,4) 与 shape(3,3,4) 兼容
c = a + b  # 逐元素相加
print("结果:\n", c)
print("结果 shape:", c.shape)


结果:
 [[[13 10  8 14]
  [15  5 15  4]
  [ 9  3 14 15]]

 [[10  8 12 12]
  [ 8  6 12  9]
  [ 1  8 12 10]]]
结果 shape: (2, 3, 4)


In [28]:
# 初始化为整型
a = np.random.randint(0, 10, size=(3, 3, 4))
b = np.random.randint(0, 10, size=(1, 1, 4))

# print(a)
# print(b)
# 广播机制自动扩展 b 的维度，使 shape(1,3,4) 与 shape(3,3,4) 兼容
c = a + b  # 逐元素相加
# print("结果:\n", c)
print("结果 shape:", c.shape)

结果 shape: (3, 3, 4)
