## 6.2.1 求和

In [3]:
import numpy as np
arr25 = np.arange(1, 13).reshape(3, 4)
print(arr25)
# 求所有数据的和
print(arr25.sum())

# 按轴求和
# axis = 0, 表示按列求和
print(arr25.sum(axis=0))

# axis=1, 表示按行求和
print(arr25.sum(axis=1))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
78
[15 18 21 24]
[10 26 42]


## 6.2.2 求平均值

In [4]:
arr25 = np.arange(1, 13).reshape(3, 4)
print(arr25)
# 1. 求所有数的平均值
print(arr25.mean())

# 2. 按轴求平均值
# axis = 0, 按列求平均值
print(arr25.mean(axis=0))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
6.5
[5. 6. 7. 8.]


## 6.2.3 求最大值

In [5]:
arr25 = np.arange(1, 13).reshape(3, 4)
print(arr25)

# 1. 求所有数的最大值
print(arr25.max())

# 2. 按轴求最大值
# axis = 0, 按列求最大值
print(arr25.max(axis=0))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
12
[ 9 10 11 12]


## 6.2.4 求最小值

In [6]:
arr25 = np.arange(1, 13).reshape(3, 4)
print(arr25)

# 1. 求所有数的最小值
print(arr25.min())

# 2. 按轴求最小值
# axis = 1, 按行求最小值
print(arr25.min(axis=1))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
1
[1 5 9]


## 6.2.5 求前缀和

In [7]:
arr25 = np.arange(1, 13).reshape(3, 4)
print(arr25)

# 1. 求所有数的前缀和
print(arr25.cumsum())

# 2. 按轴求前缀和
# axis = 1, 按行求前缀和
print(arr25.cumsum(axis=1))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  3  6 10 15 21 28 36 45 55 66 78]
[[ 1  3  6 10]
 [ 5 11 18 26]
 [ 9 19 30 42]]


### 6.2.6 最小值索引

In [8]:
arr25 = np.random.randint(0, 100, (3, 4))
print(arr25)

# 1. 求所有数的最小值索引
print(arr25.argmin())
# 2. 按轴求最小值索引
# axis = 1, 按行求最小值索引
print(arr25.argmin(axis=1))

[[98 49  2 14]
 [15 74 36 75]
 [47 63 78 39]]
2
[2 0 3]


## 6.2.7 求标准差

In [9]:
arr25 = np.arange(1, 13).reshape(3, 4)
print(arr25)

# 1. 求所有数的标准差
print(arr25.std())

# 2. 按轴求标准差
# axis = 1, 按行求标准差
print(arr25.std(axis=1))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
3.452052529534663
[1.11803399 1.11803399 1.11803399]


## 6.2.8 求极值

In [10]:
arr25 = np.arange(1, 13).reshape(3, 4)
print(arr25)

# 1. 求所有数的极值
print(np.ptp(arr25))

# 2. 按轴求极值
# axis = 1, 按行求极值
print(np.ptp(arr25, axis=1))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
11
[3 3 3]


## 7.1 数组的添加

In [11]:
arr27 = np.array([[1,2,3],[4,5,6]])
print(arr27)

# 数组的添加
# 1. 默认情况下，展开为一维数组再添加
arr28 = np.append(arr27, np.array([7,8,9]))
print(arr28)

# 2. 指定轴添加
# axis = 0, 沿着0轴添加元素
arr29 = np.append(arr27, np.array([[7,8,9]]), axis=0)
print(arr29)

# axis=1, 沿着1轴添加元素
arr30 = np.append(arr27, np.array([[7],[8]]), axis=1)
print(arr30)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3 7]
 [4 5 6 8]]


In [12]:
arr28 = np.array([[1,2,3],[4,5,6]])
print(arr28)

# 数组的插入
# 1. 默认情况下，展开为一维数组再插入
# 2. 插入的元素必须和数组的元素形状相同

# 2表示位置2
# 7表示插入7
arr29 = np.insert(arr28, 2, 7)
print(arr29)

# 指定轴插入
# axis = 0, 沿着0轴插入元素
# 索引0，表示插入第一行
arr30 = np.insert(arr28, 0, np.array([[7,8,9]]), axis=0)
print(arr30)

[[1 2 3]
 [4 5 6]]
[1 2 7 3 4 5 6]
[[7 8 9]
 [1 2 3]
 [4 5 6]]


## 7.2 数组的删除

In [14]:
arr28 = np.array([[1,2,3],[4,5,6]])
print(arr28)

# 1. 默认情况下，展开为一维数组再删除, 2表示删除索引为2的元素
arr31 = np.delete(arr28, 2)
print(arr31)
print('-'*20)

# 2. 指定轴删除
# axis = 0, 沿着0轴删除元素
# 0表示删除索引为0的元素, 也就是删除第一行
arr32 = np.delete(arr28, 1, axis=0)
print(arr32)

[[1 2 3]
 [4 5 6]]
[1 2 4 5 6]
--------------------
[[1 2 3]]


## 7.3 数组的去重

In [15]:
arr29 = np.array([1,2,3,4,5,5,5,6,7,8,9,9]).reshape(3,4)
print(arr29)

# 1. 直接去重
# 默认情况下，展开一维数组再去重，得到的也是一维数组
arr30 = np.unique(arr29)
print(arr30)

# 2. 按轴去重
# axis = 0, 沿着0轴去重
# 添加一行重复数据
arr31 = np.append(arr29, np.array([[1,2,3,4]]), axis=0)
print(arr31)

# 去重，去除重复数据
arr32 = np.unique(arr31, axis=0)
print(arr32)

[[1 2 3 4]
 [5 5 5 6]
 [7 8 9 9]]
[1 2 3 4 5 6 7 8 9]
[[1 2 3 4]
 [5 5 5 6]
 [7 8 9 9]
 [1 2 3 4]]
[[1 2 3 4]
 [5 5 5 6]
 [7 8 9 9]]


## 7.4 拼接与分割

In [16]:
# 数组的拼接
arr33 = np.array([[1,2,3],[4,5,6]])
arr34 = np.array([[7,8,9],[10,11,12]])

# 默认情况下，沿着轴0进行拼接
arr35 = np.concatenate((arr33, arr34))
print(arr35)
print('-'*20)

# 指定轴了之后，按轴1拼接
print(np.concatenate((arr33, arr34), axis=1))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
--------------------
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [ ]:
#数组的堆叠
import numpy as np
a = np.array([1, 2, 3])  # shape: (3,)
b = np.array([4, 5, 6])  # shape: (3,)
# c = np.array([7, 8, 9])  # shape: (3,)

# axis = 0，沿着0轴进行堆叠,可以1轴
np.stack([a, b], axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [28]:
import numpy as np

# 初始化2个3行4列的数组
a = np.ones((3, 4))
b = np.ones((3, 4)) * 2

# 在0轴堆叠
stack0 = np.stack([a, b], axis=0)
print("0轴堆叠后的尺寸:", stack0.shape)

# 在1轴堆叠
stack1 = np.stack([a, b], axis=1)
print("1轴堆叠后的尺寸:", stack1.shape)

# 在2轴堆叠
stack2 = np.stack([a, b], axis=2)
print("2轴堆叠后的尺寸:", stack2.shape)


0轴堆叠后的尺寸: (2, 3, 4)
1轴堆叠后的尺寸: (3, 2, 4)
2轴堆叠后的尺寸: (3, 4, 2)


In [33]:
arr36 = np.arange(1, 13).reshape(3, 4)
print(arr36)

# 1. 默认情况下，按轴0进行分割
# 3表示分割成3份
arr37_list = np.split(arr36, 3)
print(arr37_list)
print(type(arr37_list))

# 2. 按轴1进行分割
arr38 = np.split(arr36, 2, axis=1)
print(arr38)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]])]
<class 'list'>
[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12]])]


## 7.5 转置与轴滚动

In [35]:
arr39 = np.arange(0, 12).reshape(3, 4)
print("原始数组:")
print(arr39)

# 1. 转置第一种方式
arr40 = arr39.T
print("转置第一种方式:")
print(arr40)

# 2. 转置第二种方式
arr41 = np.transpose(arr39)
print("转置第二种方式:")
print(arr41)


# 4. 轴滚动
# 表示把1轴滚动到0轴的位置
arr43 = np.rollaxis(arr39, 1, 0)
print("轴滚动:")
print(arr43)

# 轴滚动第二个案例
arr44 = np.ones((3, 4, 5, 6))
print(arr44.shape)
# 表示把3轴滚动到1轴的位置
arr45 = np.rollaxis(arr44, 2, 0)
print(arr45.shape)

原始数组:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
转置第一种方式:
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
转置第二种方式:
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
轴滚动:
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
(3, 4, 5, 6)
(5, 3, 4, 6)
