In [1]:
import numpy as np

# 创建一个示例ndarray
arr = np.array([[-5, 0, 5], [10, 15, 20]])

# 使用numpy的clip函数，将数组中的值限制在3到12之间，并原地修改
np.clip(arr, 3, 12, out=arr)

print(arr)

import torch.nn as nn
nn.Linear

[[ 3  3  5]
 [10 12 12]]


torch.nn.modules.linear.Linear

In [2]:
192*16

3072

In [3]:
16*256

4096

In [4]:
16*128

2048

In [5]:
import torch

# 创建一个示例张量
x = torch.tensor([1.0, 3.5, 2.2, 7.7, 0.8])

# 取最大的3个元素及其索引
values, indices = torch.topk(x, k=3)

print("最大3个元素的值:", values)
print("最大3个元素的索引:", indices)


最大3个元素的值: tensor([7.7000, 3.5000, 2.2000])
最大3个元素的索引: tensor([3, 1, 2])


In [6]:
import torch

# 创建一个2维张量
t = torch.tensor([[10, 20, 30], [40, 50, 60]])

# index张量指定了要采集的列索引
index = torch.tensor([[2, 1],     # 从第0行取第2列和第1列
                      [0, 2]])    # 从第1行取第0列和第2列

# 使用t.gather方法
result = t.gather(dim=1, index=index)

print("原始张量:\n", t)
print("采集索引:\n", index)
print("gather结果:\n", result)


原始张量:
 tensor([[10, 20, 30],
        [40, 50, 60]])
采集索引:
 tensor([[2, 1],
        [0, 2]])
gather结果:
 tensor([[30, 20],
        [40, 60]])


In [7]:
256*6/16

96.0