# 1.归一化

In [ ]:
#归一化 ：把特征做到同一个量纲内
import numpy as np
# 导入归一化类
from sklearn.preprocessing import MinMaxScaler

# 1. 创建数据
data = np.array([[1,200],[2,300],[3,400]])
print(data)

# 2. 创建归一化类
scaler = MinMaxScaler(feature_range=(0,1))

# 3. 训练并归一化数据
data_scaled = scaler.fit_transform(data)

# 4. 显示结果
data_scaled

[[  1 200]
 [  2 300]
 [  3 400]]


array([[0. , 0. ],
       [0.5, 0.5],
       [1. , 1. ]])

# 2 标准化

In [6]:
import numpy as np
# 1. 导入标准化类
from sklearn.preprocessing import StandardScaler

# 2. 创建数据
data = np.array([[1,200],[2,300],[3,400]])

# 3. 创建标准化类
scaler = StandardScaler()

# 4. 训练并标准化数据
data_scaled = scaler.fit_transform(data)

print("scaler.mean_:", scaler.mean_)
print("scaler.scale_:", scaler.scale_)

# 5. 显示结果
data_scaled

scaler.mean_: [  2. 300.]
scaler.scale_: [ 0.81649658 81.64965809]


array([[-1.22474487, -1.22474487],
       [ 0.        ,  0.        ],
       [ 1.22474487,  1.22474487]])

In [7]:
# 为了得到标准化后的数据的均值和标准差
scaler1 = StandardScaler()
scaler1.fit_transform(data_scaled)
print("scaler1.mean_:", scaler1.mean_)
print("scaler1.scale_:", scaler1.scale_)


scaler1.mean_: [0. 0.]
scaler1.scale_: [1. 1.]


# 3 缺失值填充

In [8]:
import numpy as np
# 1. 导入缺失值处理的类
from sklearn.impute import SimpleImputer

# 2. 创建数据(包含缺失值)
data = np.array([[1, np.nan], [2, 300], [np.nan, 400]])

# 3. 创建缺失值处理类
# strategy: mean, median, most_frequent, constant
# mean: 使用数据的平均值填充缺失值
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')

# 4. 训练模型并预测
data_new = imputer.fit_transform(data)

# 5. 输出结果
print(data_new)

[[  1.  350. ]
 [  2.  300. ]
 [  1.5 400. ]]


In [9]:
import numpy as np
# 1. 导入缺失值处理的类
from sklearn.impute import SimpleImputer

# 2. 创建数据(包含缺失值)
data = np.array([[1, np.nan], [2, 300], [np.nan, 400]])

# 3. 创建缺失值处理类
# strategy: mean, median, most_frequent, constant
# mean: 使用数据的平均值填充缺失值
imputer = SimpleImputer(missing_values=np.nan, strategy='constant',fill_value=2)

# 4. 训练模型并预测
data_new = imputer.fit_transform(data)

# 5. 输出结果
print(data_new)

[[  1.   2.]
 [  2. 300.]
 [  2. 400.]]
